[[language]]
name = "python"
language-servers = ["pylsp", "jedi", "ruff", "ty"]
formatter = { command = ".venv/bin/ruff", args = ["format", "-"] }
auto-format = true

[language-server.pylsp]
command = ".venv/bin/pylsp"

[language-server.jedi]
command = ".venv/bin/jedi-language-server"

[language-server.ruff]
command = ".venv/bin/ruff"
args = ["server"]

[language-server.ty]
command = ".venv/bin/ty"
args = ["server"]
